# Copyright 2022 Google LLC.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

steps:
- id: 'Install kubebuilder'
  name: 'golang:1.18'
  args: ['/bin/sh', './tests/install-kubebuilder.sh']
  waitFor: ['-']
- id: 'go mod download'
  name: 'golang:1.18'
  args: ['go', 'mod', 'download']
  waitFor: ['Install kubebuilder']
- id: 'go test'
  name: 'golang:1.18'
  args: ['go', 'test', './...', '-coverprofile', 'cover.out']
  waitFor: ['go mod download', 'Install kubebuilder']
- id: 'go vet'
  name: 'golang:1.18'
  args: ['go', 'vet', './...']
  waitFor: ['go mod download', 'Install kubebuilder']
- id: 'go fmt'
  name: 'golang:1.18'
  args: ['/bin/sh', '-c', '[ -z $(gofmt -l ./) ]']
  waitFor: ['go mod download', 'Install kubebuilder']
options:
  machineType: N1_HIGHCPU_8
  volumes:
  - name: go-modules
    path: /go
  - name: kubebuilder
    path: /kubebuilder
  env:
  - K8S_VERSION=1.24.1
  - KUBEBUILDER_ASSETS=/kubebuilder
