# permissions for end users to edit fqdnnetworkpolicies.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: fqdnnetworkpolicy-editor-role
rules:
- apiGroups:
  - networking.gke.io
  resources:
  - fqdnnetworkpolicies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - networking.gke.io
  resources:
  - fqdnnetworkpolicies/status
  verbs:
  - get
